AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: tea API written with spark with the aws-serverless-java-container library

Resources:
  TeaUnAuthGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: shop-un-auth-swagger.yaml
      StageName: UnAuth
      Variables:
        LambdaFunctionName: !Ref TeaUnAuthFunction

  TeaUnAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cenxui.shop.web.app.aws.lambda.handlers.UnAuthLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/application-1.0-SNAPSHOT.zip
      MemorySize: 512
      Environment:
        Variables:
          Cloud: aws
          Region: ap-northeast-1
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess # todo modify it
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref TeaUnAuthGatewayApi
            Path: /{proxy+}
            Method: any

Outputs:
  TeaUnAuthApi:
    Description: URL for application
    Value: !Sub 'https://${TeaUnAuthGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/UnAuth/index'
    Export:
      Name: TeaUnAuthApi

