AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Federate access from Cognito user Pools to CensUser , not recomand to use
Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: CensUsers
      AliasAttributes:
        - "email"
      AutoVerifiedAttributes:
        - "email"
#      Schema:
#        - AttributeDataType: "String"
#          Name: email
#          Required: True
  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
        ClientName: Cens
        GenerateSecret: false
        UserPoolId: !Ref CognitoUserPool
        WriteAttributes:
          - "email"
  CognitoIdPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName: !Ref AWS::StackName
      CognitoIdentityProviders:
        -
          ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName
      AllowUnauthenticatedIdentities: false

  AuthRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Federated:
                - "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud:
                - !Ref CognitoIdPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr:
                - "authenticated"
      Path: "/"
  AuthRoleAttach:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref CognitoIdPool
      Roles:
        authenticated: !GetAtt AuthRole.Arn
Outputs:

  CognitoIdentityPool:
    Description: <Cognito Identity Pool>
    Value: !Ref CognitoIdPool
  CognitoUserPool:
    Description: <Cognito User Pool>
    Value: !Ref CognitoUserPool
  CognitoUserPoolClient:
    Description: <Cognito User Pool App>
    Value: !Ref CognitoUserPoolClient
  CognitoIdentityAuthRole:
    Description: <Cognito Identity IAM Auth Role>
    Value: !Ref AuthRole