AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Pet Store API written with spark with the aws-serverless-java-container library
Resources:
  TeaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cenxui.tea.app.aws.lambda.handlers.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/tea-1.0-SNAPSHOT.zip
      MemorySize: 512
      Environment:
        Variables:
          OrderTableURL: 1234567
          ProductTableURL : 7658301
          Region: ap-northeast-1
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  TeaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/index'
    Export:
      Name: TeaApi