AWSTemplateFormatVersion: "2010-09-09"
Description: tea application dynamodb order table
Resources:
  teaOrder:
    Type: "AWS::DynamoDB::Table"

    Properties:
      AttributeDefinitions:
        -
          AttributeName: "mail"
          AttributeType: "S"
        -
          AttributeName: "orderDateTime"
          AttributeType: "N"
        -
          AttributeName: "bankInformation"
          AttributeType: "S"
        -
          AttributeName: "paidDate"
          AttributeType: "S"
        -
          AttributeName: "paidTime"
          AttributeType: "S"
        -
          AttributeName: "processingDate"
          AttributeType: "S"
        -
          AttributeName: "shippedDate"
          AttributeType: "S"
        -
          AttributeName: "shippedTime"
          AttributeType: "S"
        -
          AttributeName: "owner"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "mail"
          KeyType: "HASH"
        -
          AttributeName: "orderDateTime"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "teaOrder"

      GlobalSecondaryIndexes:
        -
          IndexName: "bankIndex"
          KeySchema:
          -
            AttributeName: "bankInformation"
            KeyType: "HASH"
          Projection:
            ProjectionType: "ALL" #modify todo INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        -
          IndexName: "paidIndex"
          KeySchema:
          -
            AttributeName: "paidDate"
            KeyType: "HASH"
          -
            AttributeName: "paidTime"
            KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "price"
              - "paidTime"
              - "paymentMethod"
              - "shippedDate"
              - "shippedTime"
            ProjectionType: "INCLUDE" #todo INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        -
          IndexName: "processingIndex"
          KeySchema:
          -
            AttributeName: "processingDate"
            KeyType: "HASH"
          -
            AttributeName: "owner"
            KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "products"
              - "receiver"
              - "shippingWay"
              - "shippingAddress"
              - "comment"
              - "phone"
            ProjectionType: "INCLUDE" #modify todo
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        -
          IndexName: "shippedIndex"
          KeySchema:
          -
            AttributeName: "shippedDate"
            KeyType: "HASH"
          -
            AttributeName: "shippedTime"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL" #modify todo KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
