AWSTemplateFormatVersion: "2010-09-09"
Resources:
  teaProduct:
    Type: "AWS::DynamoDB::Table"

    Properties:
      AttributeDefinitions:
        -
          AttributeName: "productName"
          AttributeType: "S"
        -
          AttributeName: "version"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "productName"
          KeyType: "HASH"
        -
          AttributeName: "version"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "teaProduct"