AWSTemplateFormatVersion: "2010-09-09"
Resources:
  teaOrder:
    Type: "AWS::DynamoDB::Table"

    Properties:
      AttributeDefinitions:
        -
          AttributeName: "mail"
          AttributeType: "S"
        -
          AttributeName: "orderDateTime"
          AttributeType: "S"
        -
          AttributeName: "paidDate"
          AttributeType: "S"
        -
          AttributeName: "paidTime"
          AttributeType: "S"
        -
          AttributeName: "processingDate"
          AttributeType: "S"
        -
          AttributeName: "shippedDate"
          AttributeType: "S"
        -
          AttributeName: "shippedTime"
          AttributeType: "S"
        -
          AttributeName: "owner"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "mail"
          KeyType: "HASH"
        -
          AttributeName: "orderDateTime"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "teaOrder"

      GlobalSecondaryIndexes:
        -
          IndexName: "paidIndex"
          KeySchema:
          -
            AttributeName: "paidDate"
            KeyType: "HASH"
          -
            AttributeName: "paidTime"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL" #modify todo
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        -
          IndexName: "processingIndex"
          KeySchema:
          -
            AttributeName: "processingDate"
            KeyType: "HASH"
          -
            AttributeName: "owner"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        -
          IndexName: "shippedIndex"
          KeySchema:
          -
            AttributeName: "shippedDate"
            KeyType: "HASH"
          -
            AttributeName: "shippedTime"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL" #modify todo
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
